# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      # Push events to branches matching refs/heads/releases/10
      - 'master'
jobs:
 
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
     
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}
        

      - name: Deploy package to digitalocean
        uses: appleboy/ssh-action@v0.1.4
        env:
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          envs: GIT_USERNAME, GIT_TOKEN
          script: |
            cd /opt/myapp \
            && git add -A \
            && git stash \
            && git pull https://$GIT_USERNAME:$GIT_TOKEN@github.com/Caarya-Github/Sportzi-backend.git deployed \
            && cp ../.env . \
            && docker build -t my-node-image . \
            && docker stop my-node-app \
            && docker run --rm -d -p 5000:5000 --name my-node-app my-node-image
